### ISSUE TITLE
Using the Dockerfile does not seem to work

### ISSUE THREAD

**Issue by MasterWayZ** [mozilla/releases_insights#37]
Using the dockerfile spits out this error: `Fatal error: Uncaught IntlException: datefmt_create: time zone id 'Europe/Amsterdam' extracted from ext/date DateTimeZone not recognized: U_ILLEGAL_ARGUMENT_ERROR in /app/vendor/twig/intl-extra/IntlExtension.php:340`
For the full error see https://mozrelease.caprover.mmgict.nl/ (I have it running there so you can see the full stacktrace).

**Comment by pascalchevrel** [comment]
I can't seem to be able to reproduce it and the app has significantly changed over the last year and should default to UTC everywhere now. I am closing it but feel free to reopen if you can still reproduce, thanks.
