### ISSUE TITLE
docker build fails due to missing directory

### ISSUE THREAD

**Issue by rachaelcrook** [mozilla/releases_insights#46]
Running "docker build ." fails with the following error:

cp: can't create 'public/style/': Is a directory
Script cp vendor/benhall14/php-calendar/html/css/calendar.css public/style/ handling the post-install-cmd event returned with error code 1
------
executor failed running [/bin/sh -c cd /app &&     composer install --no-dev --no-interaction]: exit code: 1

After adding in a line to create the above directory, the image creates successfully. 

RUN mkdir -p /app/public/assets
RUN mkdir -p /app/public/style  # <<<-- here
COPY composer* /app/
RUN cd /app && \
    composer install --no-dev --no-interaction

Result:

 => [runner 17/20] COPY --from=builder --chown=app:app /app/vendor /app/vendor                                                                                 0.5s
 => [runner 18/20] WORKDIR /app                                                                                                                                0.0s
 => [runner 19/20] RUN php docker/version.php "$source" "$version" "$commit" "$build" > public/version.json                                                    0.1s
 => [runner 20/20] COPY docker/heartbeat.php /app/public                                                                                                       0.0s
 => exporting to image                                                                                                                                         0.6s
 => => exporting layers                                                                                                                                        0.6s
 => => writing image sha256:53454172c7e4c03906a412321becfb28af0002b5ba7979f848194fc956095280                                                                   0.0s

**Comment by pascalchevrel** [comment]
Thanks, the Docker file was updated with the creation of this directory.
