### ISSUE TITLE
website is broken 

### ISSUE THREAD

**Issue by lissyx** [mozilla/releases_insights#50]
For me the main entry point https://whattrainisitnow.com is just white page. The code we have at https://github.com/mozilla/process-top-crashes/actions/runs/5874169649/job/15947783430 is also reporting failures (`req.ok` is not `True`)  when querying for versions.

**Comment by lissyx** [comment]
Looks to be intermittent, a fifth retry works

**Comment by pascalchevrel** [comment]
I am on PTO and on the go, this is likely bad cached data so should be back
to normal after cache expiration (15mn), if bot please ping relman on slack
or ask our sre team for a redeploy (that will empty the.entire cache)

**Comment by lissyx** [comment]
I'm also on parental leave otherwise I'd pinged people directly 🥴

**Comment by pascalchevrel** [comment]
This is fixed by a redeploy, it wasn't a caching issue as the 500 errors were intermittent and the cache should have long expired. There was also no sentry alert and no recent code changes, so it doesn't seem code related. Maybe the docker image was in a bad state.
