### ISSUE TITLE
Add note about last potential sec-approval for last beta uplift (beta 9) in the future releases pages

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/releases_insights#52]
The badge for ["last beta uplift"](https://github.com/mozilla/releases_insights/blob/master/app/views/templates/future_release.html.twig#L249C93-L249C93) should also include a note that we will stop being able to do sec-approvals at that point.

Background is that we sometimes get asked about late sec-approvals when the last beta has already been built. How we do sec approvals was explained in dev-platform a longer while ago. https://github.com/mozilla/releases_insights/blob/master/app/views/templates/future_release.html.twig#L249C93-L249C93

I'm happy to supply a pull request but wasn't sure about a) wording and b) how extra text would look like on the homepage, so I'm holding off on that until there's more clarity.

**Comment by pascalchevrel** [comment]
@mozfreddyb would something like that work for you?
![image](https://github.com/mozilla/releases_insights/assets/454375/4d4e9976-6e2b-4783-848f-f76ff8c90c2f)

![image](https://github.com/mozilla/releases_insights/assets/454375/f12670cd-d568-4a37-829e-a563d5c534cd)

**Comment by pascalchevrel** [comment]
I put a branch with these changes on this staging site, if it looks OK to you I can push it to production: https://stage.whattrainisitnow.nonprod.webservices.mozgcp.net/release/?version=beta

**Comment by pascalchevrel** [comment]
![image](https://github.com/mozilla/releases_insights/assets/454375/e853ffd5-a773-4f40-8bc5-2f7c9fcf3f39)

Slightly reworded + more mobile-friendly version

**Comment by mozfreddyb** [comment]
The image doesn't work but the preview on staging looks great! Thanks @pascalchevrel :)

**Comment by pascalchevrel** [comment]
This is on prod :)
