### ISSUE TITLE
Feature request: show adoption rate on release page

### ISSUE THREAD

**Issue by sidvishnoi** [mozilla/releases_insights#60]
It would be useful to show adoption rate of given release on release pages, e.g. https://whattrainisitnow.com/release/?version=128.0

The data is available (https://data.firefox.com/dashboard/user-activity#metric-overview-5), but I think showing per-release data on this site would be a good addition.

What I'm looking for is, at present date (or week), what percent of Firefox users have this version installed. i.e. those that haven't updated to a newer version. Showing that has a chart (which I think would like like a hill `_^_`) make interpretation even simpler.

**Comment by pascalchevrel** [comment]
The problem with https://data.firefox.com/dashboard/user-activity#metric-overview-5 is that this data is crunched every 2 weeks, not daily.

What I can do at least is show the adoption rate for the latest release, as this data is computed daily. 
For example:![image](https://github.com/user-attachments/assets/698c4e56-345c-4a50-b2d3-0e65fd6ee2d2)

It doesn't respond exactly to your request but it is doable I think and should give you the most interesting number, the % of our use base that are on the latest release (with the caveat that it doesn't take our ESR population -our long term support branch for enterprise- into account).

**Comment by sidvishnoi** [comment]
Only latest release data would be helpful enough too!

However, is only latest release data computed daily? How about last 2-3 releases?

**Comment by pascalchevrel** [comment]
The latest release is computed daily yes, I'll see in a second step if a separate page with adoption rate per release would be easy to do.

**Comment by pascalchevrel** [comment]
This is done, thanks for the feedback!

**Comment by sidvishnoi** [comment]
Awesome! Thank you Pascal! That was quick!
